### ISSUE TITLE
Searchbar Visibility Bug

### ISSUE THREAD

**Issue by r-m-schulz** [finnjclancy/flights#17]
The search bars for the dates class (for days and range) the searchbar stays on the screen even after the user queries has been inputted. So we have the wanted output (a scroll text output or a pie/barchart) and above that the searchbar still exist 
![IMG_8185](https://github.com/finnjclancy/flights/assets/163133650/60aac3f0-46b2-42d2-bbbe-c8f3a966c7d3)

**Comment by postolav** [comment]
It seems like the textfields themselves remain on the succeeding chart page, while the searchbar PNGs go away.

**Comment by postolav** [comment]
See if .AutoClear() for the textfields being set to false have anything to do with the issue.

> It seems like the textfields themselves remain on the succeeding chart page, while the searchbar PNGs go away.
